name: Terraform Validate

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  terraform:
    name: Validate Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.6.0'

      - name: Change to Terraform Directory
        run: cd terraform

      - name: Terraform Initialization
        run: terraform init

      - name: Terraform Validate
        run: terraform validate